<?php
    /** @var \Vaimo\MusicCheckout\Block\Customer\Widget\HouseApartment $block */
    $house = 'house';
    $apartment = 'apartment';
?>
<div class="field custom">
    <label for="<?php echo $block->escapeHtml($block->getFieldId($house)); ?>" class="label">
        <span><?php echo $block->escapeHtml($block->getFieldLabel($house)); ?></span>
    </label>
    <div class="control">
        <input type="text"
               class="input-text"
               id="<?php echo $block->escapeHtml($block->getFieldId($house)); ?>"
               name="<?php echo $block->escapeHtml($block->getFieldName($house)); ?>"
               value="<?php echo $block->escapeHtml($block->getValue($house)); ?>"
               title="<?php echo $block->escapeHtml($block->getFieldLabel($house)); ?>"
            <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>
            <?php if($block->isRequired($house)) echo 'data-validate="{required:true}"' ?>
        >
    </div>
</div>
<div class="field custom">
    <label for="<?php echo $block->escapeHtml($block->getFieldId($apartment)); ?>" class="label">
        <span><?php echo $block->escapeHtml($block->getFieldLabel($apartment)); ?></span>
    </label>
    <div class="control">
        <input type="text"
               class="input-text"
               id="<?php echo $block->escapeHtml($block->getFieldId($apartment)); ?>"
               name="<?php echo $block->escapeHtml($block->getFieldName($apartment)); ?>"
               value="<?php echo $block->escapeHtml($block->getValue($apartment)); ?>"
               title="<?php echo $block->escapeHtml($block->getFieldLabel($apartment)); ?>"
            <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>
            <?php if($block->isRequired($apartment)) echo 'data-validate="{required:true}"' ?>
        >
    </div>
</div>
