<?php
/**
 * @var $block Vaimo\Events\Block\Index\Index;
 */
?>
<?php $eventsCollection = $block->getEventsCollection(); ?>
<div id="events-section" class="events-section">
    <div class="section-title"><?php echo __('Events') ?></div>

    <div class="events">
        <?php foreach ($eventsCollection as $event) { ?>
            <?php if ($event->getIsActive()) : ?>
                <div class="event" data-id="<?= $event->getVaimoEventsEventId(); ?>">
                    <div class="event-img">
                        <?php if ($event->getImage()) : ?>
                            <img class="image"
                                 src="<?= $block->getImageUrl($event->getImage()); ?>" alt="Event" />
                        <?php else : ?>
                            <img class="image"
                                 src="<?= $block->getViewFileUrl('Vaimo_Events::images/banner_img1.jpg'); ?>" alt="Event" />
                        <?php endif; ?>
                    </div>
                    <div class="event-title"><?= $event->getTitle(); ?></div>
                    <div class="event-event-time"><?= $event->getEventTime(); ?></div>
                    <div class="event-description"><?= $event->getDescription(); ?></div>
                    <div class="event-action-wrapper">
                        <a href="#" class="action primary js-modal-toggle">Sign up</a>
                    </div>
                </div>
            <?php endif; ?>
        <?php } ?>
    </div>
</div>


<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass: 'events-modal',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: 'hidden',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('.events-popup')),
                eventBlock = null,
                eventID = null,
                eventName = '';

            $('.js-modal-toggle').on('click', function (e) {
                e.preventDefault();
                eventBlock = this.closest('.event');
                eventID = $(eventBlock).data('id');
                eventName = $(eventBlock).find('.event-title').text();

                $('.events-popup input[name=vaimo_events_event_id]').attr('value', eventID).change();
                $('.events-popup input[name=event_name]').attr('value', eventName);
                $('.events-popup').modal('openModal');
            });
        }
    );
</script>
