<div class="banner slider" data-mage-init='{"slider": {}}'>
    <div class="slider-item">
        <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img1.jpg'); ?>" alt="alt">
    </div>
    <div class="slider-item">
        <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img2.jpg'); ?>" alt="alt">
    </div>
    <div class="slider-item">
        <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img3.jpg'); ?>" alt="alt">
    </div>
    <div class="slider-item">
        <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img4.jpg'); ?>" alt="alt">
    </div>
    <div class="slider-item">
        <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img5.jpg'); ?>" alt="alt">
    </div>
</div>