<div class="fotorama" data-mage-init='{"slider": {}}'>
    <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img1.jpg'); ?>" alt="alt">
    <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img2.jpg'); ?>" alt="alt">
    <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img3.jpg'); ?>" alt="alt">
    <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img4.jpg'); ?>" alt="alt">
    <img src="<?php echo $block->getViewFileUrl('images/banner/banner_img5.jpg'); ?>" alt="alt">
</div>