<?php
/**
 * Copyright © Vaimo, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<ul class="footer links">
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/privacy-policy-cookie-restriction-mode/"><?= __('Guitars') ?></a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/search/term/popular/"><?= __('Drums') ?></a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/sales/guest/form/"><?= __('Keyboards & Pianos') ?></a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/contact/"><?= __('Music and Textbook') ?></a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/catalogsearch/advanced/" data-action="advanced-search"><?= __('Equipment') ?></a>
    </li>
</ul>