<?php
/**
 * Copyright © Vaimo, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-contacts">
    <address><?= __('Plehanivska st, 40') ?></address>
    <a href="tel:+389998887766"><?= __('38 (999) 888-77-66') ?></a>
    <a href="tel:+389998887766"><?= __('38 (999) 888-77-66') ?></a>
    <a href="mailto:music@gmail.com"><?= __('music@gmail.com') ?></a>
</div>
