<ul class="footer links">
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/privacy-policy-cookie-restriction-mode/">Guitars</a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/search/term/popular/">Drums</a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/sales/guest/form/">Keyboards & Pianos</a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/contact/">Music and Textbook</a>
    </li>
    <li class="nav item">
        <a href="http://devbox.vaimo.test/m2/catalogsearch/advanced/" data-action="advanced-search">Equipment</a>
    </li>
</ul>