<?php

namespace Vaimo\Events\DataProvider;

use Magento\Ui\DataProvider\AbstractDataProvider;
use Vaimo\Events\Model\ResourceModel\Event\Collection;

class DataProvider extends AbstractDataProvider
{
    public function __construct( Collection $collection, $name, $primaryFieldName, $requestFieldName, array $meta = [], array $data = [])
    {
        $this->collection = $collection;

        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function getData()
    {
        return []; // TODO: Change the autogenerated stub
    }
}